OPTIONS = [
    'Particles',
    'Numbers',
    'Autosave',
    'Autoupdate',
    'Milk',
    'Fancy graphics',
    'Warn before closing',
    'Cursors',
    'Focus',
    'Short numbers',
    'Notifications',
    'Wobbly cookie',
    'Alt font',
    'CSS filters',
    'Alt cookie sound',
    'Icon crates',
    'Show Backup Warning',
    'Extra buttons',
    'Lump confirmation',
    'Custom grandmas',
    'Sleep mode timeout',
    'Cloud saving',
    'Music in background',
    'Scary stuff',
    'Fullscreen',
    'Screen reader mode',
    'Discord presence',
]

BUILDINGS = [
    'Cursor',
    'Grandma',
    'Farm',
    'Mine',
    'Factory',
    'Bank',
    'Temple',
    'Wizard tower',
    'Shipment',
    'Alchemy lab',
    'Portal',
    'Time machine',
    'Antimatter condenser',
    'Prism',
    'Chancemaker',
    'Fractal engine',
    'Javascript console',
    'Idleverse',
    'Cortex baker',
    'You',
]

MINIGAME_NAMES = {
    'Farm': 'Garden',
    'Bank': 'Stock Market',
    'Temple': 'Pantheon',
    'Wizard tower': 'Grimoire',
}

SEEDS = [
    'Baker\'s Wheat',
    'Thumbcorn',
    'Cronerice',
    'Gildmillet',
    'Ordinary clover',
    'Golden clover',
    'Shimmerlily',
    'Elderwort',
    'Bakeberry',
    'Chocoroot',
    'White chocoroot',
    'White mildew',
    'Brown mold',
    'Meddleweed',
    'Whiskerbloom',
    'Chimerose',
    'Nursetulip',
    'Drowsyfern',
    'Wardlichen',
    'Keenmoss',
    'Queenbeet',
    'Juicy queenbeet',
    'Duketater',
    'Crumbspore',
    'Doughshroom',
    'Glovemorel',
    'Cheapcap',
    'Fool\'s bolete',
    'Wrinklegill',
    'Green rot',
    'Shriekbulb',
    'Tidygrass',
    'Everdaisy',
    'Ichorpuff',
]

STOCK_SYMBOLS = [
    'CRL',
    'CHC',
    'BTR',
    'SUG',
    'NUT',
    'SLT',
    'VNL',
    'EGG',
    'CNM',
    'CRM',
    'JAM',
    'WCH',
    'HNY',
    'CKI',
    'RCP',
    'SBD',
    'PBL',
    'YOU',
]

BUFFS = [
    'Frenzy',
    'Elder frenzy',
    'Clot',
    'Dragon harvest',
    'Everything must go',
    'Cursed finger',
    'Click frenzy',
    'Dragonflight',
    'Cookie storm',
    'Building buff',
    'Building debuff',
    'Sugar blessing',
    'Haggler\'s luck',
    'Haggler\'s misery',
    'Crafty pixies',
    'Nasty goblins',
    'Magic adept',
    'Magic inept',
    'Devastation',
    'Sugar frenzy',
    'Loan 1',
    'Loan 1 (interest)',
    'Loan 2',
    'Loan 2 (interest)',
    'Loan 3',
    'Loan 3 (interest)',
    'Gifted out',
]

ACHIEVEMENTS = [
    'Wake and bake',
    'Making some dough',
    'So baked right now',
    'Fledgling bakery',
    'Affluent bakery',
    'World-famous bakery',
    'Cosmic bakery',
    'Galactic bakery',
    'Universal bakery',
    'Timeless bakery',
    'Infinite bakery',
    'Immortal bakery',
    'Don\'t stop me now',
    'You can stop now',
    'Cookies all the way down',
    'Overdose',

    'Casual baking',
    'Hardcore baking',
    'Steady tasty stream',
    'Cookie monster',
    'Mass producer',
    'Cookie vortex',
    'Cookie pulsar',
    'Cookie quasar',
    'Oh hey, you\'re still here',
    'Let\'s never bake again',

    'Sacrifice',
    'Oblivion',
    'From scratch',

    'Neverclick',
    'Clicktastic',
    'Clickathlon',
    'Clickolympics',
    'Clickorama',

    'Click',
    'Double-click',
    'Mouse wheel',
    'Of Mice and Men',
    'The Digital',

    'Just wrong',
    'Grandma\'s cookies',
    'Sloppy kisses',
    'Retirement home',

    'Bought the farm',
    'Reap what you sow',
    'Farm ill',

    'Production chain',
    'Industrial revolution',
    'Global warming',

    'You know the drill',
    'Excavation site',
    'Hollow the planet',

    'Expedition',
    'Galactic highway',
    'Far far away',

    'Transmutation',
    'Transmogrification',
    'Gold member',

    'A whole new world',
    'Now you\'re thinking',
    'Dimensional shift',

    'Time warp',
    'Alternate timeline',
    'Rewriting history',

    'One with everything',
    'Mathematician',
    'Base 10',

    'Golden cookie',
    'Lucky cookie',
    'A stroke of luck',

    'Cheated cookies taste awful',
    'Uncanny clicker',

    'Builder',
    'Architect',
    'Enhancer',
    'Augmenter',

    'Cookie-dunker',

    'Fortune',
    'True Neverclick',

    'Elder nap',
    'Elder slumber',

    'Elder',

    'Elder calm',

    'Engineer',

    'Leprechaun',
    'Black cat\'s paw',

    'Nihilism',

    'Antibatter',
    'Quirky quarks',
    'It does matter!',

    'Upgrader',

    'Centennial',

    'Hardcore',

    'Speed baking I',
    'Speed baking II',
    'Speed baking III',
    'Getting even with the oven',
    'Now this is pod-smashing',
    'Chirped out',
    'Follow the white rabbit',

    'Clickasmic',

    'Friend of the ancients',
    'Ruler of the ancients',

    'Wholesome',

    'Just plain lucky',

    'Itchscratcher',
    'Wrinklesquisher',
    'Moistburster',

    'Spooky cookies',

    'Coming to town',
    'All hail Santa',
    'Let it snow',
    'Oh deer',
    'Sleigh of hand',
    'Reindeer sleigher',

    'Perfected agriculture',
    'Ultimate automation',
    'Can you dig it',
    'Type II civilization',
    'Gild wars',
    'Brain-split',
    'Time duke',
    'Molecular maestro',

    'Lone photon',
    'Dazzling glimmer',
    'Blinding flash',
    'Unending glow',

    'Lord of Constructs',
    'Lord of Progress',
    'Bicentennial',

    'Lovely cookies',

    'Centennial and a half',

    'Tiny cookie',

    'You win a cookie',

    'Click delegator',
    'Gushing grannies',
    'I hate manure',
    'Never dig down',
    'The incredible machine',
    'And beyond',
    'Magnum Opus',
    'With strange eons',
    'Spacetime jigamaroo',
    'Supermassive',
    'Praise the sun',

    'Clickageddon',
    'Clicknarok',

    'Extreme polydactyly',
    'Dr. T',

    'The old never bothered me anyway',
    'Homegrown',
    'Technocracy',
    'The center of the Earth',
    'We come in peace',
    'The secrets of the universe',
    'Realm of the Mad God',
    'Forever and ever',
    'Walk the planck',
    'Rise and shine',

    'God complex',
    'Third-party',

    'Dematerialize',
    'Nil zero zilch',
    'Transcendence',
    'Obliterate',
    'Negative void',

    'The hunt is on',
    'Egging on',
    'Mass Easteria',
    'Hide & seek champion',

    'What\'s in a name',

    'Pretty penny',
    'Fit the bill',
    'A loan in the dark',
    'Need for greed',
    'It\'s the economy, stupid',
    'Your time to shrine',
    'Shady sect',
    'New-age cult',
    'Organized religion',
    'Fanaticism',
    'Bewitched',
    'The sorcerer\'s apprentice',
    'Charms and enchantments',
    'Curses and maledictions',
    'Magic kingdom',

    'Vested interest',
    'New world order',
    'Hocus pocus',

    'Finger clickin\' good',
    'Panic at the bingo',
    'Rake in the dough',
    'Quarry on',
    'Yes I love technology',
    'Paid in full',
    'Church of Cookiology',
    'Too many rabbits, not enough hats',
    'The most precious cargo',
    'The Aureate',
    'Ever more hideous',
    'Be kind, rewind',
    'Infinitesimal',
    'A still more glorious dawn',

    'Rebirth',

    'Here you go',

    'Resurrection',
    'Reincarnation',
    'Endless cycle',

    'The agemaster',
    'To oldly go',

    'Gardener extraordinaire',
    'Tectonic ambassador',
    'Rise of the machines',
    'Acquire currency',
    'Zealotry',
    'The wizarding world',
    'Parsec-masher',
    'The work of a lifetime',
    'A place lost in time',
    'Heat death',
    'Microcosm',
    'Bright future',

    'Here be dragon',

    'How?',
    'The land of milk and cookies',
    'He who controls the cookies controls the universe',
    'Tonight on Hoarders',
    'Are you gonna eat all that?',
    'We\'re gonna need a bigger bakery',
    'In the mouth of madness',
    'Brought to you by the letter 🍪',

    'A world filled with cookies',
    'When this baby hits 36 quadrillion cookies per hour',
    'Fast and delicious',
    'Cookiehertz : a really, really tasty hertz',
    'Woops, you solved world hunger',
    'Turbopuns',
    'Faster menner',
    'And yet you\'re still hungry',
    'The Abakening',
    'There\'s really no hard limit to how long these achievement names can be and to be quite honest I\'m rather curious to see how far we can go.<br>Adolphus W. Green (1844–1917) started as the Principal of the Groton School in 1864. By 1865, he became second assistant librarian at the New York Mercantile Library; from 1867 to 1869, he was promoted to full librarian. From 1869 to 1873, he worked for Evarts, Southmayd & Choate, a law firm co-founded by William M. Evarts, Charles Ferdinand Southmayd and Joseph Hodges Choate. He was admitted to the New York State Bar Association in 1873.<br>Anyway, how\'s your day been?',
    'Fast',

    'Bicentennial and a half',

    'Tabloid addiction',

    'Clickastrophe',
    'Clickataclysm',

    'Thumbs, phalanges, metacarpals',

    'Polymath',

    'The elder scrolls',

    'To crumbs, you say?',

    'Seedy business',
    'Freak fracking',
    'Modern times',
    'The nerve of war',
    'Wololo',
    'And now for my next trick, I\'ll need a volunteer from the audience',
    'It\'s not delivery',
    'Gold, Jerry! Gold!',
    'Forbidden zone',
    'cookie clicker forever and forever a hundred years cookie clicker, all day long forever, forever a hundred times, over and over cookie clicker adventures dot com',
    'Scientists baffled everywhere',
    'Harmony of the spheres',

    'Last Chance to See',

    'Early bird',
    'Fading luck',

    'Eldeer',

    'Dude, sweet',
    'Sugar rush',
    'Year\'s worth of cavities',
    'Hand-picked',
    'Sugar sugar',
    'All-natural cane sugar',
    'Sweetmeats',

    'Tricentennial',

    'Knead for speed',
    'Well the cookies start coming and they don\'t stop coming',
    'I don\'t know if you\'ve noticed but all these icons are very slightly off-center',
    'The proof of the cookie is in the baking',
    'If it\'s worth doing, it\'s worth overdoing',

    'The dreams in which I\'m baking are the best I\'ve ever had',
    'Set for life',

    'You and the beanstalk',
    'Romancing the stone',
    'Ex machina',
    'And I need it now',
    'Pray on the weak',
    'It\'s a kind of magic',
    'Make it so',
    'All that glitters is gold',
    'H̸̷͓̳̳̯̟͕̟͍͍̣͡ḛ̢̦̰̺̮̝͖͖̘̪͉͘͡ ̠̦͕̤̪̝̥̰̠̫̖̣͙̬͘ͅC̨̦̺̩̲̥͉̭͚̜̻̝̣̼͙̮̯̪o̴̡͇̘͎̞̲͇̦̲͞͡m̸̩̺̝̣̹̱͚̬̥̫̳̼̞̘̯͘ͅẹ͇̺̜́̕͢s̶̙̟̱̥̮̯̰̦͓͇͖͖̝͘͘͞',  # this is not ascii, be careful
    'Way back then',
    'Exotic matter',
    'At the end of the tunnel',

    'Click (starring Adam Sandler)',
    'Frantiquities',
    'Overgrowth',
    'Sedimentalism',
    'Labor of love',
    'Reverse funnel system',
    'Thus spoke you',
    'Manafest destiny',
    'Neither snow nor rain nor heat nor gloom of night',
    'I\'ve got the Midas touch',
    'Which eternal lie',
    'D&eacute;j&agrave; vu',
    'Powers of Ten',
    'Now the dark days are gone',

    'Freaky jazz hands',
    'Methuselah',
    'Huge tracts of land',
    'D-d-d-d-deeper',
    'Patently genius',
    'A capital idea',
    'It belongs in a bakery',
    'Motormouth',
    'Been there done that',
    'Phlogisticated substances',
    'Bizarro world',
    'The long now',
    'Chubby hadrons',
    'Palettable',

    'Bibbidi-bobbidi-boo',
    'I\'m the wiz',
    'A wizard is you',

    'Four-leaf cookie',

    'Lucked out',
    'What are the odds',
    'Grandma needs a new pair of shoes',
    'Million to one shot, doc',
    'As luck would have it',
    'Ever in your favor',
    'Be a lady',
    'Dicey business',

    'Fingers crossed',
    'Just a statistic',
    'Murphy\'s wild guess',

    'Let\'s leaf it at that',

    'The ultimate clickdown',

    'Aged well',
    '101st birthday',
    'But wait \'til you get older',
    'Harvest moon',
    'Mine?',
    'In full gear',
    'Treacle tart economics',
    'Holy cookies, grandma!',
    'The Prestige',
    'That\'s just peanuts to space',
    'Worth its weight in lead',
    'What happens in the vortex stays in the vortex',
    'Invited to yesterday\'s party',
    'Downsizing',
    'My eyes',
    'Maybe a chance in hell, actually',

    'Make like a tree',
    'Cave story',
    'In-cog-neato',
    'Save your breath because that\'s all you\'ve got left',
    'Vengeful and almighty',
    'Spell it out for you',
    'Space space space space space',
    'Don\'t get used to yourself, you\'re gonna have to change',
    'Objects in the mirror dimension are closer than they appear',
    'Groundhog day',
    'A matter of perspective',
    'Optical illusion',
    'Jackpot',

    'So much to do so much to see',

    'Running with scissors',
    'Rarefied air',
    'Push it to the limit',
    'Green cookies sleep furiously',

    'Panic! at Nabisco',
    'Bursting at the seams',
    'Just about full',
    'Hungry for more',

    'All the other kids with the pumped up clicks',
    'One...more...click...',

    'Botany enthusiast',
    'Green, aching thumb',
    'In the garden of Eden (baby)',

    'Keeper of the conservatory',
    'Seedless to nay',

    'You get nothing',
    'Humble rebeginnings',
    'The end of the world',
    'Oh, you\'re back',
    'Lazarus',

    'Leisurely pace',
    'Hypersonic',

    'Feed me, Orteil',
    'And then what?',

    'Tricentennial and a half',
    'Quadricentennial',
    'Quadricentennial and a half',

    'Quincentennial',

    'Maillard reaction',

    'When the cookies ascend just right',

    'With her finger and her thumb',

    'Defense of the ancients',
    'Sharpest tool in the shed',
    'Hey now, you\'re a rock',
    'Break the mold',
    'Get the show on, get paid',
    'My world\'s on fire, how about yours',
    'The meteor men beg to differ',
    'Only shooting stars',
    'We could all use a little change',
    'Your brain gets smart but your head gets dumb',
    'The years start coming',
    'What a concept',
    'You\'ll never shine if you don\'t glow',
    'You\'ll never know if you don\'t go',

    'Self-contained',
    'Threw you for a loop',
    'The sum of its parts',
    'Bears repeating',
    'More of the same',
    'Last recurse',
    'Out of one, many',
    'An example of recursion',
    'For more information on this achievement, please refer to its title',
    'I\'m so meta, even this achievement',
    'Never get bored',

    'The needs of the many',
    'Eating its own',
    'We must go deeper',

    'Sierpinski rhomboids',

    'Gotta go fast',
    'I think it\'s safe to say you\'ve got it made',

    'Renaissance baker',

    'Veteran',

    'Thick-skinned',

    'F12',
    'Variable success',
    'No comments',
    'Up to code',
    'Works on my machine',
    'Technical debt',
    'Mind your language',
    'Inconsolable',
    'Closure',

    'Dude what if we\'re all living in a simulation like what if we\'re all just code on a computer somewhere',
    'Taking the back streets',

    'Inherited prototype',
    'A model of document object',
    'First-class citizen',

    'Alexandria',

    'Bake him away, toys',
    'You\'re #1 so why try harder',
    'Haven\'t even begun to peak',
    'A sometimes food',
    'Not enough of a good thing',
    'Horn of plenty',

    'Smurf account',
    'If at first you don\'t succeed',

    'O Fortuna',

    'Initial public offering',
    'Rookie numbers',
    'No nobility in poverty',
    'Full warehouses',
    'Make my day',
    'Buy buy buy',
    'Gaseous assets',
    'Pyramid scheme',

    'Jellicles',

    'Quincentennial and a half',

    'What did we even eat before these',
    'Heavy flow',
    'More you say?',
    'Large and in charge',
    'Absolutely stuffed',
    'It\'s only wafer-thin',

    'Clickety split',
    'Gotta hand it to you',
    'Okay boomer',
    'Overripe',
    'Rock on',
    'Self-manmade man',
    'Checks out',
    'Living on a prayer',
    'Higitus figitus migitus mum',
    'The incredible journey',
    'Just a phase',
    'Don\'t let me leave, Murph',
    'Caveman to cosmos',
    'Particular tastes',
    'A light snack',
    'Tempting fate',
    'Tautological',
    'Curly braces',

    'Seven horseshoes',

    'Olden days',

    'The devil\'s workshop',
    'In the green',
    'Mountain out of a molehill, but like in a good way',
    'The wheels of progress',
    'That\'s rich',
    'Preaches and cream',
    'Magic thinking',
    'Is there life on Mars?',
    'Bad chemistry',
    'Reduced to gibbering heaps',
    'Back already?',
    'Nuclear throne',
    'Making light of the situation',
    'Flip a cookie. Chips, I win. Crust, you lose.',
    'In and of itself',
    'Duck typing',

    'They\'ll never know what hit \'em',
    'Well-versed',
    'Ripe for the picking',
    'Unreal',
    'Once you\'ve seen one',
    'Spoils and plunder',
    'Nobody exists on purpose, nobody belongs anywhere',
    'Hyperspace expressway',
    'Versatile',
    'You are inevitable',
    'Away from this place',
    'Everywhere at once',
    'Reject reality, substitute your own',

    'Fringe',
    'Coherence',
    'Earth-616',

    'Strange topologies',

    'Grand design',
    'Ecumenopolis',

    'The full picture',
    'When there\'s nothing left to add',

    'Sexcentennial',

    'Keep going until I say stop',
    'But I didn\'t say stop, did I?',
    'With unrivaled fervor',
    'Think big',
    'Hypersize me',
    'Max capacity',

    'Liquid assets',

    'Stifling the press',

    'It\'s big brain time',
    'Just my imagination',
    'Now there\'s an idea',
    'The organ that named itself',
    'Gyrification',
    'A trademarked portmanteau of "imagination" and "engineering"',
    'Mindfulness',
    'The 10% myth',
    'Don\'t think about it too hard',
    'Though fools seldom differ',
    'Looking kind of dumb',
    'A beautiful mind',
    'Cardinal synapses',

    'Positive thinking',
    'The thought that counts',
    'Unthinkable',

    'Gifted',

    'They moistly come at night',
    'It\'s grown on you',
    'Don\'t let the walls cave in on you',
    'Replaced by robots',
    'Financial prodigy',
    'And I will pray to a big god',
    'Shosple Colupis',
    'False vacuum',
    'Metallic taste',
    'Swiss cheese',
    'But the future refused to change',
    'What\'s the dark matter with you',
    'Enlightenment',
    'Never tell me the odds',
    'Blowing an Apollonian gasket',
    'Get with the program',
    'Lost your cosmic marbles',
    'By will alone I set my mind in motion',

    'Ain\'t that a click in the head',

    'Sexcentennial and a half',

    'I am speed',
    'And on and on',
    'Fake it till you bake it',
    'History in the baking',

    'Baby it\'s old outside',

    'Myriad',

    'Kaizen',
    'Beyond quality',

    'Everything happens so much',
    'I\'ll rest when I\'m dead',
    'What do you get for the baker who has everything',
    'Bottomless pit',

    'All the stars in heaven',

    'No time like the present',

    'Can we get much higher',
    'Speed\'s the name of the game (no it\'s not it\'s called Cookie Clicker)',
    'Rainy day fund',
    'And a little extra',

    'Grandmapocalypse',
    'Wrath cookie',

    'No more room in hell',

    'In her likeness',

    'Wrinkler poker',

    'Septcentennial',

    'My own clone',
    'Multiplicity',
    'Born for this job',
    'Episode II',
    'Copy that',
    'Life finds a way',
    'Overcrowding',
    'Strength in numbers',
    'Army of me',
    'Know thyself',
    'Didn\'t make sense not to live',
    'Genetic bottleneck',
    'Despite everything, it\'s still you',
    'Everyone everywhere all at once',

    'Self-made',
    'Reproducible results',
    'That\'s all you',

    'Self-improvement',

    'And now you\'re even older',
    'Au naturel',
    'Dirt-rich',
    'Bots build bots',
    'Getting that bag',
    'The leader is good, the leader is great',
    'You don\'t think they could\'ve used... it couldn\'t have been ma-',
    'Signed, sealed, delivered',
    'Sugar, spice, and everything nice',
    'Not even remotely close to Kansas anymore',
    'I only meant to stay a while',
    'Not 20 years away forever',
    'Bright side of the Moon',
    'Riding the Mersenne twister',
    'Divide and conquer',
    'Pebcakes',
    'Greener on the other sides',
    'Where is my mind',
    'Introspection',

    'Debt evasion',

    'Oft we mar what\'s well',

    'Cookie Clicker',

    'What\'s not clicking',
    'All on deck',
    'A round of applause',
]
